// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Popravka.ba.Data;

#nullable disable

namespace PopravkaBa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.IzvrsilacKategorija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("IzvrsilacID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("KategorijaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IzvrsilacID");

                    b.HasIndex("KategorijaID");

                    b.ToTable("IzvrsilacKategorija", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Kategorija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kategorija", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.KorisnikMjesto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("KorisnikID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MjestoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("MjestoID");

                    b.ToTable("KorisnikMjesto", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Mjesto", b =>
                {
                    b.Property<int>("MjestoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MjestoID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MjestoID");

                    b.ToTable("Mjesto", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.NotifikacijaOglas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("OglasID")
                        .HasColumnType("int");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OglasID");

                    b.ToTable("NotifikacijaOglas");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Oglas", b =>
                {
                    b.Property<int>("OglasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OglasID"));

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<int>("MjestoID")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VlasnikOglasaID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OglasID");

                    b.HasIndex("MjestoID");

                    b.HasIndex("VlasnikOglasaID");

                    b.ToTable("Oglas");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasKategorija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KategorijaID")
                        .HasColumnType("int");

                    b.Property<int>("OglasID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KategorijaID");

                    b.HasIndex("OglasID");

                    b.ToTable("OglasKategorija", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasVozackaDozvola", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("OglasID")
                        .HasColumnType("int");

                    b.Property<int>("VozackaDozvola")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OglasID");

                    b.ToTable("OglasVozackaDozvola", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.PonudaUsluge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DatumOcekivanogZavrsetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPocetkaUsluge")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("IzvrsilacID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OglasUslugeID")
                        .HasColumnType("int");

                    b.Property<int>("StatusPonude")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IzvrsilacID");

                    b.HasIndex("OglasUslugeID");

                    b.ToTable("PonudaUsluge", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.PortfolioSlika", b =>
                {
                    b.Property<int>("PortfolioSlikaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortfolioSlikaID"));

                    b.Property<string>("IzvrsilacID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortfolioSlikaID");

                    b.HasIndex("IzvrsilacID");

                    b.ToTable("PortfolioSlika", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.PrijavaRadnoMjesto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MajstorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OglasID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VrijemePrijave")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("MajstorID");

                    b.HasIndex("OglasID");

                    b.ToTable("PrijavaRadnoMjesto", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Recenzija", b =>
                {
                    b.Property<int>("RecenzijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecenzijaID"));

                    b.Property<DateTime?>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumRecenzije")
                        .HasColumnType("datetime2");

                    b.Property<string>("IzvrsilacID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KlijentID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.Property<bool>("Prijavljena")
                        .HasColumnType("bit");

                    b.Property<string>("RazlogPrijave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusPrijave")
                        .HasColumnType("int");

                    b.HasKey("RecenzijaID");

                    b.HasIndex("IzvrsilacID");

                    b.HasIndex("KlijentID");

                    b.ToTable("Recenzija", null, t =>
                        {
                            t.HasCheckConstraint("CK_Recenzija_Ocjena", "Ocjena >= 1 AND Ocjena <= 5");
                        });
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.UvjetOglasa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("OglasID")
                        .HasColumnType("int");

                    b.Property<string>("TekstUvjeta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OglasID");

                    b.ToTable("UvjetOglasa", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.VerifikacijaFirme", b =>
                {
                    b.Property<int>("VerifikacioniID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerifikacioniID"));

                    b.Property<DateTime?>("DatumObrade")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPodnosenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KontaktTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicencaDjelatnosti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logotip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivFirme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdgovornaOsobaEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdgovornaOsobaIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdgovornaOsobaPozicija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdgovornaOsobaPrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdgovornaOsobaTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoreznoUvjerenje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadnoVrijeme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rjesenje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SjedisteFirme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusVerifikacije")
                        .HasColumnType("int");

                    b.Property<string>("WebStranica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VerifikacioniID");

                    b.HasIndex("FirmaID");

                    b.ToTable("VerifikacijaFirme");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Administrator", b =>
                {
                    b.HasBaseType("PopravkaBa.Domain.Models.ApplicationUser");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.IzvrsilacUsluge", b =>
                {
                    b.HasBaseType("PopravkaBa.Domain.Models.ApplicationUser");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojZavrsenihPoslova")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProsjecnaOcjena")
                        .HasColumnType("float");

                    b.Property<string>("StambeniBroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("IzvrsilacUsluge");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Klijent", b =>
                {
                    b.HasBaseType("PopravkaBa.Domain.Models.ApplicationUser");

                    b.HasDiscriminator().HasValue("Klijent");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.EmailNotifikacijaOglas", b =>
                {
                    b.HasBaseType("PopravkaBa.Domain.Models.NotifikacijaOglas");

                    b.ToTable("EmailNotifikacijaOglasa", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasMajstora", b =>
                {
                    b.HasBaseType("PopravkaBa.Domain.Models.Oglas");

                    b.Property<double>("MinCijena")
                        .HasColumnType("float");

                    b.Property<int>("TipIsplate")
                        .HasColumnType("int");

                    b.ToTable("OglasMajstora", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasRadnoMjesto", b =>
                {
                    b.HasBaseType("PopravkaBa.Domain.Models.Oglas");

                    b.Property<int>("BrojIzvrsilaca")
                        .HasColumnType("int");

                    b.Property<int>("BrojPrijava")
                        .HasColumnType("int");

                    b.Property<int>("MaxPrihod")
                        .HasColumnType("int");

                    b.Property<int>("MinPrihod")
                        .HasColumnType("int");

                    b.Property<int>("TipIsplate")
                        .HasColumnType("int");

                    b.Property<int>("VrstaZaposlenja")
                        .HasColumnType("int");

                    b.ToTable("OglasRadnoMjesto", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasUsluge", b =>
                {
                    b.HasBaseType("PopravkaBa.Domain.Models.Oglas");

                    b.Property<int>("BrojPrijava")
                        .HasColumnType("int");

                    b.Property<int>("MaxBudzet")
                        .HasColumnType("int");

                    b.Property<int>("MinBudzet")
                        .HasColumnType("int");

                    b.ToTable("OglasUsluge", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.EmailVerifikacijaFirme", b =>
                {
                    b.HasBaseType("PopravkaBa.Domain.Models.VerifikacijaFirme");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EmailVerifikacijaFirme", (string)null);
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Firma", b =>
                {
                    b.HasBaseType("PopravkaBa.Domain.Models.IzvrsilacUsluge");

                    b.Property<DateOnly>("DatumOsnivanja")
                        .HasColumnType("date");

                    b.Property<int>("MaxZaposlenih")
                        .HasColumnType("int");

                    b.Property<int>("MinZaposlenih")
                        .HasColumnType("int");

                    b.Property<string>("NazivFirme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadnoVrijeme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusVerifikacije")
                        .HasColumnType("int");

                    b.Property<string>("WebStranica")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Firma");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Majstor", b =>
                {
                    b.HasBaseType("PopravkaBa.Domain.Models.IzvrsilacUsluge");

                    b.HasDiscriminator().HasValue("Majstor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopravkaBa.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.IzvrsilacKategorija", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.IzvrsilacUsluge", "Izvrsilac")
                        .WithMany("Kategorije")
                        .HasForeignKey("IzvrsilacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopravkaBa.Domain.Models.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izvrsilac");

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.KorisnikMjesto", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.ApplicationUser", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopravkaBa.Domain.Models.Mjesto", "Mjesto")
                        .WithMany()
                        .HasForeignKey("MjestoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Mjesto");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.NotifikacijaOglas", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.Oglas", "Oglas")
                        .WithMany("Notifikacije")
                        .HasForeignKey("OglasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Oglas", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.Mjesto", "Mjesto")
                        .WithMany()
                        .HasForeignKey("MjestoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopravkaBa.Domain.Models.ApplicationUser", "VlasnikOglasa")
                        .WithMany("Oglasi")
                        .HasForeignKey("VlasnikOglasaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mjesto");

                    b.Navigation("VlasnikOglasa");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasKategorija", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopravkaBa.Domain.Models.Oglas", "Oglas")
                        .WithMany()
                        .HasForeignKey("OglasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasVozackaDozvola", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.OglasRadnoMjesto", "Oglas")
                        .WithMany("VozackeDozvole")
                        .HasForeignKey("OglasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.PonudaUsluge", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.IzvrsilacUsluge", "Izvrsilac")
                        .WithMany("Ponude")
                        .HasForeignKey("IzvrsilacID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PopravkaBa.Domain.Models.OglasUsluge", "OglasUsluge")
                        .WithMany("Ponude")
                        .HasForeignKey("OglasUslugeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izvrsilac");

                    b.Navigation("OglasUsluge");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.PortfolioSlika", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.IzvrsilacUsluge", "Izvrsilac")
                        .WithMany("SlikePortfolija")
                        .HasForeignKey("IzvrsilacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izvrsilac");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.PrijavaRadnoMjesto", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.Majstor", "Majstor")
                        .WithMany("PrijaveZaRadnoMjesto")
                        .HasForeignKey("MajstorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PopravkaBa.Domain.Models.OglasRadnoMjesto", "OglasRadnoMjesto")
                        .WithMany("Prijave")
                        .HasForeignKey("OglasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Majstor");

                    b.Navigation("OglasRadnoMjesto");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Recenzija", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.IzvrsilacUsluge", "Izvrsilac")
                        .WithMany("Recenzije")
                        .HasForeignKey("IzvrsilacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopravkaBa.Domain.Models.Klijent", "Klijent")
                        .WithMany("Recenzije")
                        .HasForeignKey("KlijentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Izvrsilac");

                    b.Navigation("Klijent");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.UvjetOglasa", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.OglasRadnoMjesto", "Oglas")
                        .WithMany("Uvjeti")
                        .HasForeignKey("OglasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.VerifikacijaFirme", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.Firma", "Firma")
                        .WithMany("ZahtjeviVerifikacije")
                        .HasForeignKey("FirmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.EmailNotifikacijaOglas", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.NotifikacijaOglas", null)
                        .WithOne()
                        .HasForeignKey("PopravkaBa.Domain.Models.EmailNotifikacijaOglas", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasMajstora", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.Oglas", null)
                        .WithOne()
                        .HasForeignKey("PopravkaBa.Domain.Models.OglasMajstora", "OglasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasRadnoMjesto", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.Oglas", null)
                        .WithOne()
                        .HasForeignKey("PopravkaBa.Domain.Models.OglasRadnoMjesto", "OglasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasUsluge", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.Oglas", null)
                        .WithOne()
                        .HasForeignKey("PopravkaBa.Domain.Models.OglasUsluge", "OglasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.EmailVerifikacijaFirme", b =>
                {
                    b.HasOne("PopravkaBa.Domain.Models.VerifikacijaFirme", null)
                        .WithOne()
                        .HasForeignKey("PopravkaBa.Domain.Models.EmailVerifikacijaFirme", "VerifikacioniID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.ApplicationUser", b =>
                {
                    b.Navigation("Oglasi");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Oglas", b =>
                {
                    b.Navigation("Notifikacije");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.IzvrsilacUsluge", b =>
                {
                    b.Navigation("Kategorije");

                    b.Navigation("Ponude");

                    b.Navigation("Recenzije");

                    b.Navigation("SlikePortfolija");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Klijent", b =>
                {
                    b.Navigation("Recenzije");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasRadnoMjesto", b =>
                {
                    b.Navigation("Prijave");

                    b.Navigation("Uvjeti");

                    b.Navigation("VozackeDozvole");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.OglasUsluge", b =>
                {
                    b.Navigation("Ponude");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Firma", b =>
                {
                    b.Navigation("ZahtjeviVerifikacije");
                });

            modelBuilder.Entity("PopravkaBa.Domain.Models.Majstor", b =>
                {
                    b.Navigation("PrijaveZaRadnoMjesto");
                });
#pragma warning restore 612, 618
        }
    }
}
